import client from "@/lib/backend/client";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { cookies, headers } from "next/headers";
import ClientLayout from "./ClientLayout";
import "./globals.css";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout({
                                             children,
                                         }: Readonly<{
    children: React.ReactNode;
}>) {
    const headersList = await headers();

    const me = {
        id: headersList.get("x-member-id")
            ? parseInt(headersList.get("x-member-id")!)
            : 0,
        nickname: decodeURIComponent(headersList.get("x-member-nickname") || ""),
        createDate: headersList.get("x-member-create-date") || "",
        modifyDate: headersList.get("x-member-modify-date") || "",
    };

    return (
        <html lang="ko">
        <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col min-h-[100dvh] border-[5px]`}
        >
        <ClientLayout me={me}>{children}</ClientLayout>
        </body>
        </html>
    );
}