spring:
  datasource:
    url: jdbc:h2:mem:medium_test;MODE=MYSQL
  jpa:
    hibernate:
      ddl-auto: create
custom:
  site:
    baseUrl: "http://localhost:80"
  tempDirPath: D:/temp/Kotlin_Boot
  genFile:
    dirPath: D:/temp/Kotlin_Boot