server:
  port: 8021
spring:
  config:
    import: "classpath:application-common-readonly.yml"
  datasource:
    url: jdbc:h2:./db_dev;MODE=MySQL
    username: sa
    password:
    driver-class-name: org.h2.Driver