spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: trade-service
    version: 1.0.0 # 애플리케이션 버전

  redis:
    host: localhost
    port: 6379
    password: 1234  # Redis 비밀번호
    connect-timeout: 2000ms  # 연결 타임아웃
    client-type: lettuce  # Redis 클라이언트 타입 명시
    lettuce:
      pool:
        max-active: 10  # 최대 연결 수
        max-idle: 5     # 최대 유휴 연결 수
        min-idle: 1     # 최소 유휴 연결 수
        max-wait: 500ms # 최대 대기 시간

  batch:
    job:
      enabled: false

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    cache: false
    check-template-location: true

  web:
    resources:
      chain:
        strategy:
          content:
            enabled: true
            paths: /**
  messages:
    basename: messages  # 메시지 소스 설정
  profiles:
    active: prod
    include: secret
  servlet:
    multipart:
      max-file-size: 900MB
      max-request-size: 900MB
  threads:
    virtual:
      enabled: true
  mvc:
    contentnegotiation:
      media-types:
        js: application/javascript
        css: text/css
  jpa:
    properties:
      org:
        hibernate:
          envers:
            audit_table_suffix: _HISTORY
            revision_field_name: REV
            revision_type_field_name: REV_TYPE
      hibernate:
        default_batch_fetch_size: 100
        format_sql: true
        highlight_sql: true
        use_sql_comments: true
        envers:
          audit_table_suffix: _hist
          revision_field_name: rev_id
          revision_type_field_name: rev_type
          store_data_at_delete: true
logging:
  level:
    com.krstudy.kapi: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
    org.hibernate.orm.jdbc.extract: TRACE
    org.springframework.transaction.interceptor: TRACE
    org.thymeleaf: DEBUG
    org.thymeleaf.spring6: DEBUG


custom:
  resource:
    version: ${spring.application.version}
  site:
    name: sleekydz86
    baseUrl: "http://localhost:${server.port}"
  tempDirPath: D:/temp
  genFile:
    dirPath: D:/temp/Kotlin_Boot
springdoc:
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    operations-sorter: alpha
    tags-sorter: alpha
    path: /swagger-ui.html
    disable-swagger-default-url: true
    display-query-params-without-oauth2: true
api:
  key: ON_SECRET