spring:
  application:
    name: trade-service
    version: 1.0.0 # 애플리케이션 버전

  redis:
    host: localhost
    port: 6379

  resources:
    cache:
      period: 3600 # 캐시 유효 시간(초)
    chain:
      strategy:
        content:
          enabled: true
          paths: /**/*.css,/**/*.js # 버전 관리할 리소스 패턴
  batch:
    job:
      enabled: false
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
    mode: HTML5
    encoding: UTF-8
  profiles:
    active: prod
    include: secret
  servlet:
    multipart:
      max-file-size: 900MB
      max-request-size: 900MB
  threads:
    virtual:
      enabled: true
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  jpa:
    properties:
      hibernate:
        default_batch_fetch_size: 100
        format_sql: true
        highlight_sql: true
        use_sql_comments: true
        envers:
          audit_table_suffix: _hist
          revision_field_name: rev_id
          revision_type_field_name: rev_type
          store_data_at_delete: true
logging:
  level:
    com.krstudy.kapi: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
    org.hibernate.orm.jdbc.extract: TRACE
    org.springframework.transaction.interceptor: TRACE
    org.thymeleaf: DEBUG
    org.thymeleaf.spring6: DEBUG


custom:
  site:
    name: sleekydz86
    baseUrl: "http://localhost:${server.port}"
  tempDirPath: D:/temp
  genFile:
    dirPath: D:/temp/Kotlin_Boot
springdoc:
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    operations-sorter: alpha
    tags-sorter: alpha
    path: /swagger-ui.html
    disable-swagger-default-url: true
    display-query-params-without-oauth2: true
api:
  key: ON_SECRET