server:
  shutdown: graceful
  port: 8090
  servlet:
    session:
      timeout: 30m
spring:
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

  datasource:
    url: jdbc:mysql://localhost:3307/msa
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      poolName: Hikari
      max-lifetime: 1800000
      auto-commit: false
      maximum-pool-size: 5
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
    validation-query: select 1
    test-on-borrow: true
    schema: classpath:db/migration/k_db.sql
    initialization-mode: always

  jpa:
    hibernate:
      ddl-auto: create-drop
      dialect: org.hibernate.dialect.MySQL8Dialect

logging:
  level:
    com.ll.medium: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: INFO
    org.hibernate.orm.jdbc.extract: INFO
    org.springframework.transaction.interceptor: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: DEBUG

custom:
  tempDirPath: /gen/temp
  site:
    baseUrl: "https://www.sleekydz86.gg"
  genFile:
    dirPath: /gen