spring:
  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB
      enabled: true
  datasource:
    url: ENC(qXemxCa3my3RKjdYPQRxW9kewiGUV0R+qCHPPtD136vMVMGqx4WEBnMTLtuCDlpM)   # 데이터소스 URL (암호화)
    username: ENC(0jmA2aAIm8hZtPDAuVDetlYEi+IKEkdK)                              # 사용자명 (암호화)
    password: ENC(F3MPinPpKSMmTiLtN5wKwQ==)                                      # 비밀번호 (암호화)
    driver-class-name: org.postgresql.Driver                                     # JDBC 드라이버
    hikari:
      poolName: Hikari                                                           # HikariCP 이름
      max-lifetime: 1800000                                                      # 최대 생명 주기
      auto-commit: false                                                         # 자동 커밋 비활성화
      maximum-pool-size: 5                                                       # 최대 풀 크기
      data-source-properties:
        cachePrepStmts: true                                                     # Prepared Statement 캐시 활성화
        prepStmtCacheSize: 250                                                   # Prepared Statement 캐시 크기
        prepStmtCacheSqlLimit: 2048                                              # Prepared Statement SQL 제한
    validation-query: select 1                                                   # 유효성 검사 쿼리
    test-on-borrow: true                                                         # 대여 시 유효성 검사 활성화
    initialization-mode: always                                                  # 초기화 모드 설정
    read-only: false
  jpa:
    defer-datasource-initialization: false
    show-sql: true
    hibernate:
      ddl-auto: create-drop                                                     # 기존 테이블 유지 안 하고 매번 새로 생성 후 삭제
    properties:
      hibernate:
        jdbc:
          batch_size: 50
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    open-in-view: true
jasypt:
  encryptor:
    password: your-secret-password                                              # 여기에 실제 비밀번호를 설정하세요.